# Generated by Django 4.1.3 on 2022-12-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(blank=True, max_length=2000, verbose_name='Comentario')),
                ('me_gusta', models.BooleanField(default=False)),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='noticia.noticia')),
            ],
        ),
    ]
