# Generated by Django 4.1.4 on 2022-12-20 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.CharField(max_length=2000, verbose_name='Comentario')),
                ('cant_likes', models.PositiveIntegerField(default=0)),
                ('noticia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='noticia.noticia')),
            ],
        ),
    ]
