# Generated by Django 4.1.4 on 2022-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='cant_likes',
            field=models.BooleanField(default=False),
        ),
    ]
