# Generated by Django 4.1.4 on 2022-12-20 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_alter_comentarios_cant_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='cant_likes',
            new_name='like',
        ),
    ]
