# Generated by Django 4.1.4 on 2022-12-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_rename_cant_likes_comentarios_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentarios',
            field=models.CharField(max_length=2000, null=True, verbose_name='Comentario'),
        ),
    ]
