# Generated by Django 4.1.4 on 2022-12-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0005_alter_comentarios_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentarios',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Comentario'),
        ),
    ]
