# Generated by Django 4.1.4 on 2022-12-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0006_alter_comentarios_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentarios',
            old_name='like',
            new_name='me_gusta',
        ),
    ]
