# Generated by Django 4.1.4 on 2022-12-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.BooleanField(verbose_name='admin')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('celular', models.IntegerField(verbose_name='celular')),
                ('fecha_de_nacimiento', models.DateField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('fecha_hora_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
