# Generated by Django 4.1.3 on 2022-12-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(null=True, upload_to='noticia'),
        ),
    ]
