# Generated by Django 4.1.3 on 2022-12-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0003_alter_noticia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='noticia', verbose_name='ImageNoticia'),
        ),
    ]
